### ISSUE TITLE
Don't use /settings sub-folder for API call

### ISSUE THREAD

**Issue by iDuuck** [felicianotech/pointless#16]
I am receiving multiple calls to `/settings`. If I am using the same API call without `/settings` I am getting a valid result. Just check this repo. I am always receiving the "This project is not built on CircleCI".

**Comment by felicianotech** [comment]
What do you mean by "you are receiving"? Could you provide a bit more detail?

The extension itself calls `/project/<VCS>/<org>/<repo>/setttings` to CircleCI's website to get information on the current project being viewed and if that project is even on CircleCI. If the project is not, there may be a 404 but that's expected.

If you have a project **you know** is on CircleCI but the extension is not picking up the build status, did you follow the Configuring instructions in the [README](https://github.com/felicianotech/pointless#configuring)?

**Comment by iDuuck** [comment]
I supposed this repository *is* on CircleCI as a public project. Though, the project shows "This project is not built on CircleCI".

**Comment by felicianotech** [comment]
Can you provide a screenshot?

**Comment by iDuuck** [comment]
<img width="477" alt="screen shot 2017-09-14 at 10 23 28 am 2" src="https://user-images.githubusercontent.com/325241/30419493-d82f2826-9936-11e7-8e04-e8140c9296f9.png">

**Comment by felicianotech** [comment]
I believe this issue is fixes in #24.

The fix should be shipped in Pointless v17.11.0.
