### ISSUE TITLE
Private repos lost their green/red sphere

### ISSUE THREAD

**Issue by ryanwohara** [felicianotech/pointless#59]
It seems that GH updated their UI and broke the ability to show the success status on private repositories. It is still functional as expected on any public repository.

**Comment by felicianotech** [comment]
They actually broke it for public repos too but I already fixed it. I missed it on private repos.

I'll try to get this fixed today.

**Comment by felicianotech** [comment]
@ryanwohara The fix will be available in version 2007.2.
